### ISSUE TITLE
Mention of name with space character (with two or more words)

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#263]
_what happens_

When I try to tag a name that has two or more words (i.e. has at least one space character in name), Coracle name auto-suggest exits. 

<img width="238" alt="Screenshot 2024-02-07 at 2 23 15 PM" src="https://github.com/coracle-social/coracle/assets/64376233/8ac71b70-5e89-460f-a574-7bcc8e6679e0">

<img width="182" alt="Screenshot 2024-02-07 at 2 23 10 PM" src="https://github.com/coracle-social/coracle/assets/64376233/e868d024-5560-4519-a950-2232e4e1d83a">

**Comment by staab** [comment]
Known issue, but yeah, worth fixing.

**Comment by alltheseas** [comment]
> Known issue, but yeah, worth fixing.

Apologize if duplicate - could not find in the issues list

**Comment by staab** [comment]
> Apologize if duplicate - could not find in the issues list

Nope, helpful to have it cataloged

**Comment by zmjohnso** [comment]
I believe this issue has been fixed and can be closed. When I try and tag the person mentioned about now: 
<img width="517" alt="image" src="https://github.com/user-attachments/assets/0f64f905-89fa-498b-97c1-036b35b45904">
It shows up fine in the suggestions and can be clicked to tag that person.
<img width="520" alt="image" src="https://github.com/user-attachments/assets/4a099916-7f22-44b3-a8e9-27066cc2f5ea">
Of course, the search string breaks when you add a space, but I think this makes since. Also, this is the same behavior I get when I use Amethyst.

**Comment by staab** [comment]
Agreed, and nostr-editor has the ability to potentially change this behavior.
