### ISSUE TITLE
Update palette and theme structure

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#267]
Add neutral spectrum and tinted spectrum. Define hover states for everything. Rename our current classes to match.  Use tailwind's dark:prefix to switch theme.

![Screenshot 2024-02-09 at 1 52 03 PM](https://github.com/coracle-social/coracle/assets/2494842/257cc5ef-129a-4b9f-8530-082798c922d1)

**Comment by staab** [comment]
@dtonon any chance you could come up with the full palette for me?

**Comment by dtonon** [comment]
@staab I'm working on this

**Comment by dtonon** [comment]
This is the new proposed palette:

![image](https://github.com/coracle-social/coracle/assets/89577423/2c586cbd-c698-43e2-815d-81ee645a50ae)

For the neutral palette, I picked up the [standard Tailwind's Neutral one](https://tailwindcss.com/docs/customizing-colors), so we have a more standard background. This palette is usually used for neutral/secondary elements, e.g. the window background or the text in a colored button.

For the tinted (warm) palette, the Coracle's characteristic one, I preferred a subset of only 6 colors; otherwise with too many shades there is the risk to apply them in a haphazard manner.

The `accent` color is unique (see below the "Variants" section).

The `attention` color is for warning/danger message/actions; yellow is commonly associated with warning signs and caution internationally, so it is a good pick instead of red that is too similar to the accent color, and also exclude any problem on the accessibility side for color-blind people.

The `important` color, picked from the inverted spectrum of the `accent`, is aimed to focus important messages that need to pop up in a UI that also has accent elements.

## Variants

Often, a slight lighter or darker shade is needed, e.g. the hover or some borders. To keep the basic palette simple, I would dynamically create a -l (light) and -d (dark) version with +/-15% brightness (something like [this approach](https://github.com/tailwindlabs/discuss/issues/392)) for the tinted gradient and the accent/attention/important colors. These variations should be used only for small details.

## The colors

| Name | Hex value | Note |
| --- | --- | --- |
| accent | `#FC560E` |
| tinted-100 | `#F1EAE7` |
| tinted-200 | `#DED3CF` |
| tinted-400 | `#B9A69E` | Current `warm-d` |
| tinted-500 | `#756A65` | Current `cocoa-l` |
| tinted-600 | `#5A524F` |
| tinted-700 | `#3E3A38` | Current `cocoa` |
| attention | `#FCAB0E` |
| important | `#12D2B0` |
