### ISSUE TITLE
Better bitcoin integration

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#327]
Zaps need to be better for V4V people.

- One click zaps w/splits
- Bitcoin connect?
- Imitate Primal and use Strike API?

**Comment by stackingsaunter** [comment]
Any idea why bitcoin connect is not integrated anymore?

**Comment by staab** [comment]
I did it sort of halfway, and it created some confusion/overloading when zapping. It's still in there, just not in settings anymore. If you have webln it'll be used, but as a fallback bitcoin connect will be used. Hopefully I can do a better job the next time around.

**Comment by staab** [comment]
Yes, I'm beginning to realize that, so I could get rid of the webln integration entirely and just use BC? That would be an easy change to do. Would it make it easier to implement zap splits? I haven't ever really had time to prioritize zaps, so it's always been a back burner project for me.

**Comment by rolznz** [comment]
@staab it's ok to use Bitcoin Connect on its own as it also allows you to connect to a WebLN browser extension (which will provide the WebLN object).

Zap splits are made simple with WebLN (which is what Bitcoin Connect provides) because users do not need to confirm each payment. You can do simultaneous payments up to a budget provided by the user (NWC / setting a budget in the Alby extension / Lnbits account limit etc).
