### ISSUE TITLE
Coracle repeatedly wants me to sign a kind 10115 event on startup, it doesn't matter if i sign it or don't. 

### ISSUE THREAD

**Issue by abhay-raizada** [coracle-social/coracle#413]

**Comment by staab** [comment]
This is in order to track whether notifications have been read or not. It's a work in progress and still needs some bugs worked out, but Coracle assumes people are using "approve all" flows. It's not currently a goal to provide granular control, users just have to trust Coracle. I might revisit that at some point, but that's the trade-off I'm currently working under.
