### ISSUE TITLE
consider: do not show "open other nostr app" icon if viewing/opening kind1s

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#455]
_context_ 

Without knowing if Coracle users use the "open note in another app" link (seems unlikely, as Coracle does fine with kind1s), consider not displaying this option for notes. Instead, display for less commonly supported kinds/kinds not supported by Coracle.

https://njump.me/note15nafwgnws46p0kr373suf7vyg8j3un38p3gy3ukws6prj6ctp3as8z4vtw

**Comment by alltheseas** [comment]
![kind1coracle](https://github.com/user-attachments/assets/d419356d-f513-4d5b-bf5a-f98bc840c8af)

**Comment by staab** [comment]
The rendering architecture needs to change, since we switch on kind only within `NoteContent`. With e.g. feeds, it will make more sense to swap out rendering for the entirety of the note instead. Kind handlers should only show up on non-kind-1 notes, and probably be integrated more tightly with the content. Also use a different icon.

**Comment by alltheseas** [comment]
Different icon via Niel "open with"

![image](https://github.com/user-attachments/assets/a0b1b3b1-2c62-44a1-ae8a-bc7effaac8ea)

https://njump.me/nevent1qqst6r4q96mqysfkujexzsfm6hy3w4ht64a45mmr5wxj9wkxsjac2jgpz3mhxue69uhkummnw3ezummcw3ezuer9wcq32amnwvaz7tmwdaehgun9d35hgetn9ehhyecpzfmhxue69uhhwmm59e6hg7r09ehkuegpr9mhxue69uhhqatjv9mxjerp9ehx7um5wghxcctwvsqf6vy0
